- name: Install Python Firewalld module
  command: yum -y install python-firewall creates=/usr/lib/python*/site-packages/firewall

- name: Install firewall
  command: yum install -y firewalld creates=/usr/sbin/firewalld

- name: Make sure firewall is running
  systemd:
    name: firewalld
    state: started
    enabled: yes